# This is a basic workflow that is manually triggered

name: Check urls

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      file:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'File to parse'
        # Default value if no value is explicitly provided
        default: 'README.md'
        required: true
        type: string

jobs:
  checkup:
    runs-on: self-hosted
    steps:
    - name: Check urls
      run: |
        ls -la
        python3 ./src/checkup.py ${{ inputs.file }}
