name: Check urls

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  checkup:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Check urls
      run: python3 ./src/checkup.py README.md
