name: Check urls

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  checkup:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Check urls
      run: python3 ./src/checkup.py blog-hamradioindex/index.markdown
