name: Check urls

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'File to parse'
        default: 'README.md'
        required: true
        type: string

jobs:
  checkup:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Check urls
      run: python3 ./src/checkup.py ${{ inputs.file }}
